// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIR0YF3j_FUOiZV_IhYZtczKXaswdCQ0Q',
    appId: '1:668634890910:web:c380e52be82ccc46fef18f',
    messagingSenderId: '668634890910',
    projectId: 'ahmed2307-kellton3-1b8a9',
    authDomain: 'ahmed2307-kellton3-1b8a9.firebaseapp.com',
    storageBucket: 'ahmed2307-kellton3-1b8a9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdo1LRvC7esWj0V7YJovRLeDtEVIg7Cdg',
    appId: '1:668634890910:android:d60610704714cf25fef18f',
    messagingSenderId: '668634890910',
    projectId: 'ahmed2307-kellton3-1b8a9',
    storageBucket: 'ahmed2307-kellton3-1b8a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbOFMINi6oqz-MdH87Xnx9A-TwPFbQyNo',
    appId: '1:668634890910:ios:39c82e562fa3546efef18f',
    messagingSenderId: '668634890910',
    projectId: 'ahmed2307-kellton3-1b8a9',
    storageBucket: 'ahmed2307-kellton3-1b8a9.appspot.com',
    iosClientId: '668634890910-nu0igjrvoo7urupbilc5m4gshgotv3m2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbOFMINi6oqz-MdH87Xnx9A-TwPFbQyNo',
    appId: '1:668634890910:ios:39c82e562fa3546efef18f',
    messagingSenderId: '668634890910',
    projectId: 'ahmed2307-kellton3-1b8a9',
    storageBucket: 'ahmed2307-kellton3-1b8a9.appspot.com',
    iosClientId: '668634890910-nu0igjrvoo7urupbilc5m4gshgotv3m2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
